services:

  universityapi:
    image: universityapi
    build:
      context: ./UniversityAPI
      dockerfile: Dockerfile
    container_name: webapi
    expose:
      - 5000
    ports:
      - 5000:8080
    networks:
      - university_network
    depends_on:
      - mssql
    restart: always

  universityblazor:
    image: universityblazor
    build:
      context: ./UniversityBlazor
      dockerfile: Dockerfile
    container_name: blazor
    expose:
      - 5000
    ports:
      - 5000:8080
    networks:
      - university_network
    depends_on:
      - mssql
    restart: always

networks:
  university_network:
    driver: bridge

volumes:
  mssql_volume: